 ; --- Hardware ---

n-gpu-layers = 999

threads = 8

threads-batch = 16

; --- Batching ---

batch-size = 4096

ubatch-size = 4096

; --- Context ---

ctx-size = 65536

; --- KV Cache ---

cache-ram = 2048

; --- Server ---

parallel = 1

kv-unified = true

flash-attn = true

no-mmproj-offload = true

;no-mmap = true

; --- Sampling defaults ---

temp = 1.0

top-k = 40

top-p = 0.95

min-p = 0.01

repeat-penalty = 1.05

seed = 3407

; ==============================================

; Unsloth Qwen3.6-35B-A3B-GGUF Q6_K_XL tgs 40 pps 2100

; ==============================================

[Qwen3.6-35B-A3B-Q6_K_XL-Unsloth]

model = unsloth/Qwen3.6-35B-A3B-GGUF/models--unsloth--Qwen3.6-35B-A3B-GGUF/snapshots/a483e9e6cbd595906af30beda3187c2663a1118c/Qwen3.6-35B-A3B-UD-Q6_K_XL.gguf

mmproj = unsloth/Qwen3.6-35B-A3B-GGUF/models--unsloth--Qwen3.6-35B-A3B-GGUF/snapshots/a483e9e6cbd595906af30beda3187c2663a1118c/mmproj-BF16.gguf

ctx-size = 131072

n-cpu-moe = 35

cache-type-k = q8_0

cache-type-v = q8_0

no-mmap = true

reasoning = on

jinja = true

chat-template-kwargs = {"preserve_thinking": true}

reasoning-budget = 8096

reasoning-budget-message = Okay, enough thinking no more waiting. Let's just jump to it.

temperature = 0.6

top-p = 0.95

top-k = 20

min-p = 0.0

presence-penalty = 1.5

repeat-penalty = 1.0

swa-full = true

cache-reuse = 512

